## DESCRIPTION
#
# A Docker Compose to spin up a Kafka Development Cluster.
# This is NOT what you should use in production.
# The docker images used here are provided by Confluent Platform,
# and listed here: https://hub.docker.com/u/confluentinc/.

version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:${CP_ZOOKEEPER_VER}
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
  kafka-01:
    container_name: kafka-01
    image: confluentinc/cp-kafka:${CP_KAFKA_VER}
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 512M
    depends_on:
      - zookeeper
    ports:
      - '9091:9091'
      - '19091:19091'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-01:9091,PLAINTEXT_HOST://localhost:19091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091,PLAINTEXT_HOST://0.0.0.0:19091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ZOOKEEPER=zookeeper:2181
      - KAFKA_HEAP_OPTS=${CP_KAFKA_HEAP_OPTS}
  kafka-02:
    container_name: kafka-02
    image: confluentinc/cp-kafka:${CP_KAFKA_VER}
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 512M
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '19092:19092'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-02:9092,PLAINTEXT_HOST://localhost:19092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ZOOKEEPER=zookeeper:2181
      - KAFKA_HEAP_OPTS=${CP_KAFKA_HEAP_OPTS}
  kafka-03:
    container_name: kafka-03
    image: confluentinc/cp-kafka:${CP_KAFKA_VER}
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 512M
    depends_on:
      - zookeeper
    ports:
      - '9093:9093'
      - '19093:19093'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-03:9093,PLAINTEXT_HOST://localhost:19093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:19093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ZOOKEEPER=zookeeper:2181
      - KAFKA_HEAP_OPTS=${CP_KAFKA_HEAP_OPTS}

networks:
  default:
    name: ${NETWORK_NAME}
    driver: bridge